Toy_shopMVC/Models/ProductInBasket.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Toy_shopMVC.Models
{
    public partial class ProductInBasket
    {
        public ProductInBasket()
        {
            Orders = new HashSet<Order>();
        }

        public long CodeProductInBasket { get; set; }
        public long CodeOfProduct { get; set; }
        public int Quantity { get; set; }

        public virtual Product CodeOfProductNavigation { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}

Toy_shopMVC/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Toy_shopMVC.Models;

namespace Toy_shopMVC.Controllers
{
    public class OrdersController : Controller
    {
        private readonly Toy_shopContext _context;

        public OrdersController(Toy_shopContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var toy_shopContext = _context.Orders.Include(o => o.CodeProductInBasketNavigation)
                .ThenInclude(x=>x.CodeOfProductNavigation).Include(o => o.CodeStatusNavigation);
            return View(await toy_shopContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.CodeProductInBasketNavigation)
                .Include(o => o.CodeStatusNavigation)
                .FirstOrDefaultAsync(m => m.CodeOrder == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create(long? id)
        {
            ViewData["CodeProductInBasket"] = new SelectList(_context.ProductInBaskets, "CodeProductInBasket", "CodeProductInBasket");
            ViewData["CodeStatus"] = new SelectList(_context.Statuses, "CodeOfStatus", "Name");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CodeOrder,CodeProductInBasket,Sum,DateOfCreation,CodeStatus,Name,Phone,Comment,Email")] Order order, long id)
        {
            if (ModelState.IsValid)
            {
                order.CodeProductInBasket = id;
                order.Sum = (_context.ProductInBaskets.Where(x => x.CodeProductInBasket == id)
                    .Select(x => x.CodeOfProductNavigation.Price).FirstOrDefault()) *
                    (_context.ProductInBaskets.Where(x => x.CodeProductInBasket == id)
                    .Select(x => x.Quantity).FirstOrDefault());
                order.CodeStatus = 0;
                order.DateOfCreation = DateTime.Now;
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CodeProductInBasket"] = new SelectList(_context.ProductInBaskets, "CodeProductInBasket", "CodeProductInBasket", order.CodeProductInBasket);
            ViewData["CodeStatus"] = new SelectList(_context.Statuses, "CodeOfStatus", "Name", order.CodeStatus);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["CodeProductInBasket"] = new SelectList(_context.ProductInBaskets, "CodeProductInBasket", "CodeProductInBasket", order.CodeProductInBasket);
            ViewData["CodeStatus"] = new SelectList(_context.Statuses, "CodeOfStatus", "Name", order.CodeStatus);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("CodeOrder,CodeProductInBasket,Sum,DateOfCreation,CodeStatus,Name,Phone,Comment,Email")] Order order)
        {
            if (id != order.CodeOrder)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.CodeOrder))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CodeProductInBasket"] = new SelectList(_context.ProductInBaskets, "CodeProductInBasket", "CodeProductInBasket", order.CodeProductInBasket);
            ViewData["CodeStatus"] = new SelectList(_context.Statuses, "CodeOfStatus", "Name", order.CodeStatus);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.CodeProductInBasketNavigation)
                .Include(o => o.CodeStatusNavigation)
                .FirstOrDefaultAsync(m => m.CodeOrder == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(long id)
        {
            return _context.Orders.Any(e => e.CodeOrder == id);
        }
    }
}

Toy_shopMVC/Controllers/ProductInBasketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Toy_shopMVC.Models;

namespace Toy_shopMVC.Controllers
{
    public class ProductInBasketsController : Controller
    {
        private readonly Toy_shopContext _context;

        public ProductInBasketsController(Toy_shopContext context)
        {
            _context = context;
        }

        // GET: ProductInBaskets
        public async Task<IActionResult> Index()
        {
            var toy_shopContext = _context.ProductInBaskets.Include(p => p.CodeOfProductNavigation);
            return View(await toy_shopContext.ToListAsync());
        }

        //// GET: ProductInBaskets
        //public async Task<IActionResult> Sum()
        //{
        //    decimal sum = 0;
        //    foreach (var i in _context.ProductInBaskets)
        //    {
        //        sum += i.Quantity * i.CodeOfProductNavigation.Price;
        //    }
        //    ViewBag.Sum = sum;
        //    return View();
        //}
        // GET: ProductInBaskets/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productInBasket = await _context.ProductInBaskets
                .Include(p => p.CodeOfProductNavigation)
                .FirstOrDefaultAsync(m => m.CodeProductInBasket == id);
            if (productInBasket == null)
            {
                return NotFound();
            }

            return View(productInBasket);
        }

        // GET: ProductInBaskets/Create
        public IActionResult Create()
        {
            ViewData["CodeOfProduct"] = new SelectList(_context.Products, "CodeOfProduct", "Name");
            return View();
        }

        // POST: ProductInBaskets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("CodeProductInBasket,CodeOfProduct,Quantity")] ProductInBasket productInBasket)
        {
            if (ModelState.IsValid)
            {
                _context.Add(productInBasket);
                _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CodeOfProduct"] = new SelectList(_context.Products, "CodeOfProduct", "Name", productInBasket.CodeOfProduct);
            return View(productInBasket);
        }

        [HttpGet]
        public IActionResult ToOrder(long? id)
        {
            //ViewData["CodeProductInBasket"] = new SelectList(_context.ProductInBaskets, "CodeProductInBasket", "CodeProductInBasket");
            //ViewData["CodeStatus"] = new SelectList(_context.Statuses, "CodeOfStatus", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ToOrder([Bind("CodeProductInBasket,Sum,DateOfCreation,CodeStatus,Name,Phone,Comment,Email")] Order order, long id)
        {
            //CodeOrder,
            order.CodeProductInBasket = id;
            order.Sum = (_context.ProductInBaskets.Where(x => x.CodeProductInBasket == id)
                .Select(x => x.CodeOfProductNavigation.Price).FirstOrDefault()) *
                (_context.ProductInBaskets.Where(x => x.CodeProductInBasket == id)
                .Select(x=>x.Quantity).FirstOrDefault());
            order.DateOfCreation = DateTime.Now;
            order.CodeStatus = 0;
            _context.Add(order);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: ProductInBaskets/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productInBasket = await _context.ProductInBaskets.FindAsync(id);
            if (productInBasket == null)
            {
                return NotFound();
            }
            ViewData["CodeOfProduct"] = new SelectList(_context.Products, "CodeOfProduct", "Name", productInBasket.CodeOfProduct);
            return View(productInBasket);
        }

        // POST: ProductInBaskets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("CodeProductInBasket,CodeOfProduct,Quantity")] ProductInBasket productInBasket)
        {
            if (id != productInBasket.CodeProductInBasket)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productInBasket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductInBasketExists(productInBasket.CodeProductInBasket))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CodeOfProduct"] = new SelectList(_context.Products, "CodeOfProduct", "Name", productInBasket.CodeOfProduct);
            return View(productInBasket);
        }

        // GET: ProductInBaskets/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productInBasket = await _context.ProductInBaskets
                .Include(p => p.CodeOfProductNavigation)
                .FirstOrDefaultAsync(m => m.CodeProductInBasket == id);
            if (productInBasket == null)
            {
                return NotFound();
            }

            return View(productInBasket);
        }

        // POST: ProductInBaskets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var productInBasket = await _context.ProductInBaskets.FindAsync(id);
            _context.ProductInBaskets.Remove(productInBasket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductInBasketExists(long id)
        {
            return _context.ProductInBaskets.Any(e => e.CodeProductInBasket == id);
        }
    }
}

Toy_shopMVC/Views/ProductInBaskets/Create.cshtml
@model Toy_shopMVC.Models.ProductInBasket

@{
    ViewData["Title"] = "Create";
}


<h4>Товары в корзине</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CodeOfProduct" class="control-label"></label>
                <select asp-for="CodeOfProduct" class ="form-control" asp-items="ViewBag.CodeOfProduct"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Toy_shopMVC/Views/ProductInBaskets/Delete.cshtml
@model Toy_shopMVC.Models.ProductInBasket

@{
    ViewData["Title"] = "Delete";
}


<h3>Удалить данный товар из корзины?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Количество
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            Товар
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodeOfProductNavigation.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CodeProductInBasket" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Назад</a>
    </form>
</div>

Toy_shopMVC/Views/ProductInBaskets/Details.cshtml
@model Toy_shopMVC.Models.ProductInBasket

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ProductInBasket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodeOfProductNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodeOfProductNavigation.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CodeProductInBasket">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Toy_shopMVC/Views/ProductInBaskets/Edit.cshtml
@model Toy_shopMVC.Models.ProductInBasket

@{
    ViewData["Title"] = "Edit";
}


<h4>Товары в корзине</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CodeProductInBasket" />
            <div class="form-group">
                <label asp-for="CodeOfProduct" class="control-label">Товар</label>
                <select asp-for="CodeOfProduct" class="form-control" asp-items="ViewBag.CodeOfProduct"></select>
                <span asp-validation-for="CodeOfProduct" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label">Количество</label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Toy_shopMVC/Views/ProductInBaskets/Index.cshtml
@model IEnumerable<Toy_shopMVC.Models.ProductInBasket>

@{
    ViewData["Title"] = "Index";
}

<div class="basket">
    <h1>Корзина</h1>

    <p>
        <a asp-action="Create">Добавить товары в корзину</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Товар
                </th>
                <th>
                    Количество
                </th>
                <th>
                    Цена (руб.)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CodeOfProductNavigation.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CodeOfProductNavigation.Price)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.CodeProductInBasket">Редактировать</a> |
                    <a asp-action="Delete" asp-route-id="@item.CodeProductInBasket">Удалить</a> |
                    @*<a asp-action="ToOrder" asp-route-id="@item.CodeProductInBasket"asp-controller="ProductInBaskets">Заказать прямо сейчас</a>|*@
                    <a asp-action="Create" asp-route-id="@item.CodeProductInBasket" asp-controller="Orders">Заказать прямо сейчас</a>
                </td>
                @*<form asp-action="ToOrder" asp-route-id="@item.CodeProductInBasket">
                    <div class="form-group">
                        <input type="submit" value="Оформить" class="btn btn-primary" />
                    </div>
                </form>*@
            </tr>
            }
        </tbody>
    </table>
    <div>
        @*Итого: @ViewBag.Sum*@
        
    </div>
</div>

Toy_shopMVC/Views/ProductInBaskets/ToOrder.cshtml
@model Toy_shopMVC.Models.Order

@{
    ViewData["Title"] = "Create";
}
<h4>Подробности заказа появятся в следующем окне</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="CodeProductInBasket" class="control-label"></label>
                <select asp-for="CodeProductInBasket" class="form-control" asp-items="ViewBag.CodeProductInBasket"></select>
            </div>*@
            @*<div class="form-group">
                <label asp-for="Sum" class="control-label"></label>
                <input asp-for="Sum" class="form-control" />
                <span asp-validation-for="Sum" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
                    <label asp-for="DateOfCreation" class="control-label"></label>
                    <input asp-for="DateOfCreation" class="form-control" />
                    <span asp-validation-for="DateOfCreation" class="text-danger"></span>
                </div>*@
            @*<div class="form-group">
                <label asp-for="CodeStatus" class="control-label"></label>
                <select asp-for="CodeStatus" class="form-control" asp-items="ViewBag.CodeStatus"></select>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label">Введите имя</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label">Введите телефон</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label">Комментарий</label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Почта</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Оформить заказ" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}